### ISSUE TITLE
How to close individual clients? (Java)

### ISSUE THREAD

**Issue by spixware** [tdlib/td#356] opened 2018-09-06 19:56 UTC
Greetings, I want to build a method in the given Example.java that just sends a message in a group chat. I came to the point where this works, but after that my application is still running. So I added 

`quiting = true;`
`haveAuthorization = false;`
`client.send(new TdApi.Close(), defaultHandler);`

after my message was sent. Now I get:

> Closing
Error {
  code = 500
  message = "Internal Server Error: closing"
}

My message is not sent to the group chat until I send a second one without these 3 lines. What do I have to do to close the server connection and the client correctly after my stuff is done? Thanks

**Comment by levlam** [comment] 2018-09-06 21:00
You close TDLib before it is able to send the message. You need to wait until the message is successfully sent and close TDLib only after receiving corresponding `updateMessageSendSucceeded`/`updateMessageSendFailed`/`updateDeleteMessages`.

**Comment by MaxiGH** [comment] 2018-09-07 17:05
Thanks, I implemented these cases in the UpdatesHandler and it seems to work, but I still get a Internal server error 500 when closing the connection. My most recent problem is, that I want to have a terminating application that just sends a message and authenticates the device I'm using currently. So far so good, when I first execute the code without a authkey, because I didn't get one for the first time running on a new device, I want to get one on my phone. After that my app should terminate and close the connection. Then I'm running the same code again, providing the auth code from my phone this time. Now it should authenticate the device correctly, send the message and close afterwards again.

I tried this on my prototype, but it ended with a 24 hours block, because it kept to send requests to the api from somewhere in the code. Can you help me out with an easy example @levlam? I really appreciate your help up to this point, I feel a bit lost within these handlers and authentication methods.

**Comment by levlam** [comment] 2018-09-07 17:41
Could you collect TDLib logs of both runs with verbosity 4 and send them to @tdlib_bot? It will help me to understand, what exactly happens.

**Comment by MaxiGH** [comment] 2018-09-07 18:50
I sent 2 logs from Example.java and my app to tdlib_bot.  I'll send the other .log of my terminating app tomorow as soon as I get deblocked. Thank you for your support.

**Comment by levlam** [comment] 2019-04-29 14:14
It has happened that 24 hours flood wait was caused by the repeating calls to `checkAuthenticationCode` and often logging in and out, so there was no errors on TDLib side.

**Closed by levlam** 2019-04-29 14:14 UTC
