### ISSUE TITLE
Build of tdcore fails with linker error on windows

### ISSUE THREAD

**Issue by vlabella** [tdlib/td#2888] opened 2024-05-17 21:11 UTC
I am getting the following linker error when building on windows when trying to build the x64 bit version.  This is using the latest version of visual studio and openssl 3.3.0 and using link time optimizations /LTO.  StackOverflow suggests this maybe caused by allocating too much memory on the stack.  Any help would be appreciated

 WebPagesManager.cpp
  mtproto_api.cpp
  telegram_api.cpp
  secret_api.cpp
  GitCommitHash.cpp
C:\sandbox\libs\td-master\build-x64\Release\tdcore.lib : fatal error LNK1248: image size (1000E5B33) exceeds
maximum allowable size (FFFFFFFF) [C:\sandbox\libs\td-master\build-x64\tdcore.vcxproj]
  Building Custom Rule C:/sandbox/libs/td-master/benchmark/CMakeLists.txt

**Comment by levlam** [comment] 2024-05-17 21:19
What is you MSVC version?

Did you also change some other compiler flags, for example, replaced `/Zi` with `/Z7`?

**Comment by vlabella** [comment] 2024-05-17 22:25
Here is the version of the compiler

Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

also

VCToolsVersion=14.39.33519
VisualStudioVersion=17.0
VISUAL_STUDIO_YEAR=2022

I did not change any compiler options in the cmake file.

**Comment by levlam** [comment] 2024-05-18 05:23
> I did not change any compiler options in the cmake file.

But you have enabled LTO, so you may have changed some other options.

**Comment by levlam** [comment] 2024-05-18 10:49
I was able to reproduce the issue. It looks like the total amount of code slightly exceeded MSVC implementation limits and LTO build doesn't work anymore. The total amount of the code will continue to grow over time, so the issue can be fixed only by introducing more intermediate projects and static libraries and splitting files between them.

**Comment by vlabella** [comment] 2024-05-18 12:55
Its building now for me without LTO.  Thanks for the help.

**Comment by levlam** [comment] 2024-05-18 19:08
Yes, for now only Release build with LTO is affected. In Debug LTO build tdcore.lib is less than 2 GB, and without LTO it is less than 250 MB.

**Comment by levlam** [comment] 2024-05-28 11:58
Fixed in TDLib 1.8.30.

**Closed by levlam** 2024-05-28 11:58 UTC
