### ISSUE TITLE
Cant login via proxy

### ISSUE THREAD

**Issue by Losses** [tdlib/td#115] opened 2018-03-02 10:28 UTC
I'm using the UWP version of Telegram, Unigram, and unable to login via proxy since it switched to `tdlib`.

It's said that proxy is handled by TDLib, so I submited the issue here.

Original issue post: **https://github.com/UnigramDev/Unigram/issues/545**

**Comment by isopen** [comment] 2018-03-02 12:06
Show logs

**Comment by levlam** [comment] 2018-03-03 06:53
There is no need for logs. The issue is already fixed, the fix is coming in the next update.

**Comment by levlam** [comment] 2018-03-19 14:38
Fixed in TDLib 1.2.0.

**Closed by levlam** 2018-03-19 14:38 UTC
