### ISSUE TITLE
Can't build iOS library

### ISSUE THREAD

**Issue by istarchenkov** [tdlib/td#372] opened 2018-10-01 11:51 UTC
Get error when running build.sh

./build.sh: line 2: realpath: command not found
Platform = macOS Simulator = 
./build.sh: line 12: realpath: command not found
OpenSSL path = 
CMake Error: The source directory "/Development/TDLib/example/ios/build/build-macOS" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No rule to make target `install'.  Stop.

**Comment by jwktje** [comment] 2018-11-30 01:01
I can't get it to work. I get these errors every time. 
https://pastebin.com/rj2BmA3z

Any idea @levlam ?

**Comment by levlam** [comment] 2018-11-30 10:59
@jwktje There is a problem with OpenSSL build. Could you provide output of `./build-openssl.sh` and file `build-ios/CMakeCache.txt`?

**Comment by jwktje** [comment] 2018-11-30 22:51
Sure no problem! The sh output is after I've ran it successfully before. Is that enough info or do you need the output from an actual fresh build? 
[./build-openssl.sh output Pastebin](https://pastebin.com/jVstxTNx)
[build-ios/CMakeCache.txt Pastebin](https://pastebin.com/0yWKmKmp)

**Comment by jwktje** [comment] 2018-12-01 01:31
Did exactly that just now, and this is the full output. Error seems the same as my initial pastebin. 

https://pastebin.com/dK3pPEKE

**Comment by levlam** [comment] 2018-12-01 06:54
@jwktje Thanks, for the info. It seems that the problem is in our usage of `Python-Apple-support`, which dropped support for armv7 build of OpenSSL in https://github.com/pybee/Python-Apple-support/commit/ec1706d67ed3a01f80df53ac22d004db94a0812a. Could you replace
`git checkout 2.7`
in `build-openssl.sh` with
`git checkout 60b990128d5f1f04c336ff66594574515ab56604` and rerun it?

**Comment by jwktje** [comment] 2018-12-01 15:29
That seems to work! It builds and I get the header files. Can't find the .a files afterwards though. Where should they end up?

**Comment by Khwuanchai** [comment] 2018-12-02 00:50
I​ need​ it.

ในวันที่ อา. 2 ธ.ค. 2018 07:27 น. Aliaksei Levin <notifications@github.com>
เขียนว่า:

**Comment by AmirCa84** [comment] 2019-02-11 21:12
> @jwktje Thanks, for the info. It seems that the problem is in our usage of `Python-Apple-support`, which dropped support for armv7 build of OpenSSL in [pybee/Python-Apple-support@ec1706d](https://github.com/pybee/Python-Apple-support/commit/ec1706d67ed3a01f80df53ac22d004db94a0812a). Could you replace
> `git checkout 2.7`
> in `build-openssl.sh` with
> `git checkout 60b990128d5f1f04c336ff66594574515ab56604` and rerun it?

Thank you. it solved my issue as well.

**Comment by levlam** [comment] 2019-03-07 22:49
Alternatively you can clone and build https://github.com/ERussel/td/tree/fix/all-archs, which has similar fix.

**Comment by levlam** [comment] 2019-05-01 19:29
Fixed in TDLib 1.4.0.

**Closed by levlam** 2019-05-01 19:29 UTC
