### ISSUE TITLE
My telegram x keeps crashing

### ISSUE THREAD

**Issue by Stanleygh** [tdlib/td#1821] opened 2022-01-09 18:42 UTC
[ o|[t12][1641746646.002490997]
[SqliteConnectionSafe.cpp:21][#113][1KV] Can't open database: unable to open database file for database "/data/data/
org. thunderdog.challegram/files/tdlib111/
db.sqlite"

**Comment by levlam** [comment] 2022-01-10 11:04
This is duplicate of https://github.com/tdlib/td/issues/902. This is a Telegram X bug. See https://github.com/tdlib/td/issues/902#issuecomment-578435762 for more details.

**Closed** 2022-07-21 19:10 UTC
