### ISSUE TITLE
Is there a way to receive updateDeleteMessages for all messages in a channel?

### ISSUE THREAD

**Issue by kossnocorp** [tdlib/td#366] opened 2018-09-18 06:36 UTC
I'm building [an app that converts channels to blogs](https://telepost.io). I'm processing `updateDeleteMessages` event to properly update posts, but I'm not receiving it consistently. I assume that `updateDeleteMessages` events are sent only for last messages or messages that are still in cache. Is there a way to receive the event for all messages?

**Comment by levlam** [comment] 2018-09-18 14:06
Currently, no. In supergroups and channels some updates can be skipped if there are more than 100 missed updates. So even some UpdateNewMessage updates can be skipped and instead current chat state is sent through other updates. Possibly, I can add options, which change that behavior, but using such options will not be recommended for general usage.

**Comment by kossnocorp** [comment] 2018-09-18 14:14
@levlam what a missed update means? Unread messages or something else? If the former, will it help if I'll be marking messages as read as soon as I receive the updates?

**Comment by levlam** [comment] 2018-09-18 16:30
In channels, there can be missed `updateNewMessage`, `updateMessageContent`, `updateMessageEdited` and `updateDeleteMessages` updates if there are more than 100 of such pending updates. Other updates shouldn't be missed if the TDLib is launched at least once in a few weeks. This technique is called "channel gaps" and it exists to prevent all users to download all updates from all channels without changing user experience.

**Comment by levlam** [comment] 2018-09-18 18:00
> Sorry I still don't understand what do "pending updates" mean.
"Pending" are yet unreceived from server updates. For example, if there will be more than 100 deleted simultaneously messages and one message sent in the same time in a channel, or client will be offline for some time, so there was more than 100 missed new messages/message edits/message deletions, then these updates will not be received. There will be a "gap" in the channel and only the last channel message and other channel parameters will be fetched from the server.

**Comment by levlam** [comment] 2018-09-18 20:40
You can't specify duration of user online status, it is chosen server-side. In order to set online status you need just set option `online` after application start. Then TDLib will automatically update online status when needed.

But online status isn't related in any way to receiving of updates about messages from the server.

**Comment by levlam** [comment] 2018-09-19 21:15
No. It isn't related, because there is no issue here, only expected behavior. I'll add options, which will allow to alter this behavior.

**Comment by kossnocorp** [comment] 2018-09-20 03:58
@levlam ok, thank you a lot!

**Comment by smaznet** [comment] 2019-07-27 06:30
Is there any update for this?

**Comment by levlam** [comment] 2019-07-27 13:50
@smaznet The option is planned for TDLib 1.5.0.

**Comment by smaznet** [comment] 2019-07-27 14:56
@levlam when it will be released?

**Comment by levlam** [comment] 2019-07-27 15:09
@smaznet No ETA yet.

**Comment by levlam** [comment] 2019-09-08 01:58
Since TDLib 1.5.0 `updateDeleteMessages` is sent even for unknown messages in supergroups and channels by default, so there is no need in an option.

Maximum number of missed updates before a "channel gap" is created is an implementation detail and shouldn't be changed by the client. Hence you need to manually increase value of the [MAX_CHANNEL_DIFFERENCE](https://github.com/tdlib/td/blob/00df08f144d37a158fc37eb5f69e115492e2a423/td/telegram/MessagesManager.h#L1292) constant if you need to fetch all updates in a supergroup.

**Closed by levlam** 2019-09-08 01:58 UTC

**Comment by zyadomer98** [comment] 2021-06-14 21:16
Mr. Levlam, I have the same problem and I do not know how to solve it. I added my bot to a new channel that has only one other member. Anything I do on the channel would be immediately received as an update except for updateDeleteMessages which is only received after I stop my bot and then start it again. I am using doing it with nodejs using this library (https://github.com/Bannerets/tdl). I do not know if it is related to  MAX_CHANNEL_DIFFERENCE or not and even do not know how to change that value. What should I do?

**Comment by levlam** [comment] 2021-06-14 21:42
These updates aren't supposed to be received immediately in channels. And if you receive them after restart, then this is definitely unrelated to `MAX_CHANNEL_DIFFERENCE`.

**Comment by zyadomer98** [comment] 2021-06-15 15:29
So why it is received after restart? Is there any way to fix it?

**Comment by levlam** [comment] 2021-06-15 16:27
No, this is how updates in channels work.
