### ISSUE TITLE
Tdlib Not Sending UpdateNewChat Event for New Supergroups

### ISSUE THREAD

**Issue by Skeith94** [tdlib/td#3050] opened 2024-09-15 21:03 UTC
Hello everyone,

I’m developing a new client for Android TV (java), but I’m encountering a problem that I can't resolve at the moment. When a user joins a new supergroup from the Telegram app on their smartphone, I notice while debugging Tdlib’s behavior that I receive a "TdApi.UpdateSupergroup" event. According to the documentation, I would expect an "TdApi.UpdateNewChat" event to follow, but this does not occur. Additionally, I’ve tried a workaround for this issue. I’ve observed that Tdlib typically assigns a chatId for the supergroup as -100+supergroup.id, but despite attempting a TdApi.GetChat(id) request, I receive a 400 error. Furthermore, upon investigating, if I delete the supergroup in question, I finally receive a TdApi.UpdateNewChat event, as if Tdlib wasn’t properly synchronized with the remote counterpart. Could you please assist me with this? I am available to provide some logs of the tests I’ve conducted if it helps to resolve this issue. Thank you.

**Comment by levlam** [comment] 2024-09-16 06:48
Could you send TDLib logs with verbosity level 4 since app start to https://t.me/tdlib_bot?

**Comment by Skeith94** [comment] 2024-09-16 09:21
I've just sent the TDLib logs with verbosity level 4 since app start.

**Comment by levlam** [comment] 2024-09-16 11:37
Could you check whether the issue is fixed in the have just pushed to Github TDLib version?

**Comment by Skeith94** [comment] 2024-09-16 11:46
I'm using version 1.8.35, has a new version been released?

**Comment by levlam** [comment] 2024-09-16 11:58
The latest version on Github master is 1.8.36.

**Closed** 2024-09-16 13:02 UTC

**Comment by levlam** [comment] 2024-09-16 14:55
Thank you for the report.
