### ISSUE TITLE
Critical error TDLib. 

### ISSUE THREAD

**Issue by rodman2** [tdlib/td#1163] opened 2020-08-08 09:54 UTC
#bug
Critical error TDLib. 
![photo_2020-08-04_13-35-17](https://user-images.githubusercontent.com/69385605/89707401-39f5cd80-d976-11ea-8319-9f2cb2c395a5.jpg)

Version: 1.6.4.1361
Android: 8.0.0
[ 0][t 8][1596878218.599027157][SqliteConnectionSafe.cpp:18][#102][!Td] Can't open database of size 70656: [Error : 0 : Can't open database: [query:SELECT count(*) FROM sqlite_master] to database "/data/data/org.thunderdog.challegram/files/tdlib115/db.sqlite" failed: unable to open database file]

**Comment by levlam** [comment] 2020-08-08 17:13
Then this is a duplicate of #902. This can't be fixed on TDLib's side. You need to wait for Telegram X update with the fix, or update to Android 9.0+ if possible.

**Closed** 2020-08-28 12:51 UTC
