### ISSUE TITLE
failed: unable to open database file

### ISSUE THREAD

**Issue by EbrahimING** [tdlib/td#1037] opened 2020-05-08 06:32 UTC
[ 0][t28][1588918682.959041119][SqliteConnectionSafe.cpp:18][#77][!KV] Can't open database of size 1154048: [Error : 0 : Can't open database: [query:SELECT count(*) FROM sqlite_master] to database "/data/data/org.thunderdog.challegram/files/tdlib79/db.sqlite" failed: unable to open database file]

**Comment by levlam** [comment] 2020-05-08 09:08
How much accounts and which Android version do you have?

**Comment by EbrahimING** [comment] 2020-05-08 10:14
Hi, It's Android 8.0 O (26) . More than a hundred accounts ...

**Comment by levlam** [comment] 2020-05-08 11:14
Then this is a duplicate of https://github.com/tdlib/td/issues/902. This can't be fixed on TDLib's side. You need to wait for Telegram X update with the fix, or update to Android 9.0+ if possible.

**Comment by EbrahimING** [comment] 2020-05-08 11:19
How much accounts does Telegram X support and when will that update arrive?

**Comment by levlam** [comment] 2020-05-08 13:03
Less than 50 should work.

Noone knows when the issue will be fixed.

**Comment by levlam** [comment] 2020-11-15 21:54
Closing as a duplicate.

**Closed by levlam** 2020-11-15 21:54 UTC
