### ISSUE TITLE
Getting corrupted data

### ISSUE THREAD

**Issue by AndrewLaneX** [tdlib/td#1111] opened 2020-06-24 04:25 UTC
I'm using [Airgram](https://github.com/airgram/airgram), and when running multiple instances, I get corrupted data. I'm using a different database directory for every instance.

### Info

OS: `Ubuntu 20.04`
TDLib: `v1.6.0`
Node: `v12.16.1`
Airgram: `v3.0.2`
ffi-napi: `v3.0.1`

- https://github.com/airgram/airgram/issues/114#issuecomment-647872370
- https://github.com/airgram/airgram/issues/114#issuecomment-648521809

**Comment by levlam** [comment] 2020-06-24 05:29
See https://github.com/tdlib/td/issues/643.

This can't be currently fixed on TDLib's side, because the issue is in node-ffi and can be only workarounded by airgram.

**Comment by esindger** [comment] 2020-06-24 10:57
There is a workaround - pause all Airgram instances except the active one. You can use `airgram.provider.pause()` and `airgram.provider.resume()` methods for it.

**Comment by levlam** [comment] 2020-11-15 21:42
Closing as a duplicate of #643.

**Closed by levlam** 2020-11-15 21:42 UTC
