### ISSUE TITLE
How to let normal users know whether the group opens the telegram aggressive anti-spam function.

### ISSUE THREAD

**Issue by DeeEi** [tdlib/td#2305] opened 2023-02-14 04:37 UTC
The telegram aggressive anti-spam function is so unfriendly to some users.

And it always make some users ban and they can't speak in public though they just chat normally.

I think telegram should display it to let the normal users know whether the group opens the telegram aggressive anti-spam function.

**Comment by AYMENJD** [comment] 2023-02-14 04:58
> And it always make some users ban and they can't speak in public though they just chat normally.

You can always report aggressive anti-spam false positive in **Recent actions** section.

**Comment by DeeEi** [comment] 2023-02-14 06:46
Errr... The aggressive anti-spam is so fucking for Chinese language users.
Always wrong ban...
@spambot for unban needs to wait for a long time.

**Comment by DeeEi** [comment] 2023-02-14 06:48
So telegram should show for normal users whether the group opens the anti-spam.
And we normal users can tell the group admin to turn down anti-spam.
So fucking the function is...

**Comment by DeeEi** [comment] 2023-02-14 06:51
Please add the functions like 【This group is opening telegram aggressive anti-spam】to display for normal users...

**Comment by AYMENJD** [comment] 2023-02-14 06:53
Reporting the false positive can always help reducing **false positives**. 

Additionally, you can always turn off **Aggressive Anti-Spam** from chat settings if it doesn't suits your need.

**Comment by AYMENJD** [comment] 2023-02-14 06:54
> Please add the functions like 【This group is opening telegram aggressive anti-spam】to display for normal users...

The correct place for suggestion is: https://suggestions.telegram.org/.

**Comment by DeeEi** [comment] 2023-02-14 06:56
I'm so sorry to suggest in wrong place.
Please delete this 2305 issue...

**Comment by AYMENJD** [comment] 2023-02-14 06:58
Don't worry, closing the issue is enough.

**Comment by levlam** [comment] 2023-02-15 11:14
The users can make an appeal themselves through @SpamBot in case of a false-positive ban.

**Closed** 2023-03-09 19:37 UTC

**Comment by amkartashov** [comment] 2024-02-15 01:35
@levlam 

I'm banned and I even don't know the reason. Is it a bug or what? Spambot is useless, it justs says to wait. No option to appeal.

Writing here just I don't see any other official way to report this. my tg is t.me/ndrkrtshv

**Comment by ericbsd** [comment] 2024-07-12 23:44
> > And it always make some users ban and they can't speak in public though they just chat normally.
> 
> You can always report aggressive anti-spam false positive in **Recent actions** section.

But it does not keep the user out of trouble. I have one of the group members who is banned from public group posting.
