### ISSUE TITLE
Strange thread id

### ISSUE THREAD

**Issue by bortoz** [tdlib/td#1352] opened 2020-12-31 11:15 UTC
This is the log from my application:
```
I/DLTD    ( 8486): [ 3][t-156984272][1609408808.532363653][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 20.000000
I/DLTD    ( 8486): [ 3][t 3][1609408808.546792984][Td.cpp:4585][&td_requests]	Sending update: updateOption {
I/DLTD    ( 8486):   name = "version"
I/DLTD    ( 8486):   value = optionValueString {
I/DLTD    ( 8486):     value = "1.7.0"
I/DLTD    ( 8486):   }
I/DLTD    ( 8486): }
I/DLTD    ( 8486): [ 3][t-156984272][1609408808.553808212][Client.cpp:282][&td_requests]	End to wait for updates, returning object 0 0x20d16b0
I/DLTD    ( 8486): [ 3][t-156984272][1609408808.554538249][Client.cpp:274][&td_requests]	Begin to wait for updates with timeout 0.100000
I/DLTD    ( 8486): [ 3][t 3][1609408808.556226730][Td.cpp:4585][&td_requests]	Sending update: updateAuthorizationState {
I/DLTD    ( 8486):   authorization_state = authorizationStateWaitTdlibParameters {
I/DLTD    ( 8486):   }
I/DLTD    ( 8486): }
I/DLTD    ( 8486): [ 3][t-156984272][1609408808.556596755][Client.cpp:282][&td_requests]	End to wait for updates, returning object 0 0x21cba50
```
Is it normal to have `-156984272` as thread id?

**Comment by dima279** [comment] 2020-12-31 11:40
Супер😀🤚спасибо

Отправлено с iPhone

31 дек. 2020 г., в 13:15, Alessandro Bortolin <notifications@github.com> написал(а):

﻿

This is the log from my application:

I/DLTD    ( 8486): [ 3][t-156984272][1609408808.532363653][Client.cpp:274][&td_requests]        Begin to wait for updates with timeout 20.000000
I/DLTD    ( 8486): [ 3][t 3][1609408808.546792984][Td.cpp:4585][&td_requests]   Sending update: updateOption {
I/DLTD    ( 8486):   name = "version"
I/DLTD    ( 8486):   value = optionValueString {
I/DLTD    ( 8486):     value = "1.7.0"
I/DLTD    ( 8486):   }
I/DLTD    ( 8486): }
I/DLTD    ( 8486): [ 3][t-156984272][1609408808.553808212][Client.cpp:282][&td_requests]        End to wait for updates, returning object 0 0x20d16b0
I/DLTD    ( 8486): [ 3][t-156984272][1609408808.554538249][Client.cpp:274][&td_requests]        Begin to wait for updates with timeout 0.100000
I/DLTD    ( 8486): [ 3][t 3][1609408808.556226730][Td.cpp:4585][&td_requests]   Sending update: updateAuthorizationState {
I/DLTD    ( 8486):   authorization_state = authorizationStateWaitTdlibParameters {
I/DLTD    ( 8486):   }
I/DLTD    ( 8486): }
I/DLTD    ( 8486): [ 3][t-156984272][1609408808.556596755][Client.cpp:282][&td_requests]        End to wait for updates, returning object 0 0x21cba50


Is it normal to have -156984272 as thread id?

**Comment by levlam** [comment] 2020-12-31 12:48
@bortoz This is an unitialized global thread local variable. There was problems with thread-local variables in Tizen, but we expected that they will be zeroed at least,

**Comment by bortoz** [comment] 2020-12-31 13:32
Thanks!
Is this a real problem or are there some other thread local variables that may be causing some problems?
And if so, is there an easy fix?

**Comment by levlam** [comment] 2020-12-31 22:11
There are a lot of thread local variables, which can cause real problems if they will not be zeroed. We don't know, how to fix this behavior in Tizen, but we didn't search a lot for possible solutions or investigated its reasons.

**Comment by bortoz** [comment] 2021-01-01 01:14
Since it's strange that most of tdlib works fine despite that, I've done some tests and I found that thread-local variables were actually zero-initialized.

After hours of debugging I found the real problem. It turns out that Tizen localization has some bugs (like everything about Tizen), the problem is when double are converted to string:

https://github.com/tdlib/td/blob/dbbfcd5d6475627fa9e6e8a167e2508b8d1eace8/tdutils/td/utils/StringBuilder.cpp#L178

I replaced the `std::stringstream` with this ugly code and then thread ids were normal.

```
double integral;
double fractional = std::abs(std::modf(x.d, &integral));
current_ptr_ = print_int(current_ptr_, static_cast<long long>(integral));
*current_ptr_++ = '.';
current_ptr_ = print_uint(current_ptr_, static_cast<unsigned long long>(fractional * std::pow(10, x.precision)));
```

I don't know how these things are related. I thought maybe the problem was my locale (since in Italy we use the comma in real numbers) but it was not.

So is it possible to change that function to something that will hopefully work on Tizen?

**Comment by levlam** [comment] 2021-01-01 11:45
Uninitialized thread local variable can have any value, among which 0 is the most common. Why do you think that the problem is in  std::stringstream?

**Comment by bortoz** [comment] 2021-01-01 13:40
The problem is not `std::stringstream` itself, but the localization library. I was trying to fixing an other bug I had and I found that sometimes the application crash when tdlib tries to convert a double to string. So i tried to use my own double conversion and the application no longer crash. Moreover when I checked the log I found that ids became correct.

My opinion (not sure) is that Tizen is doing something really bad with thread-local locale (e.g. `uselocale`) and this results in undefined behavior.

I also think that if Tizen didn't initialize thread-local variabile, something worse would have happend, but it seems to me that everything works fine.

**Comment by levlam** [comment] 2021-01-01 14:26
`std::stringstream` and locales are used also in `to_double` function in td/utils/misc.cpp, so this usage should be fixed as well. Correct and fast float number printing and reading is a hard task, so we preferred to use a standard library implementation for that. For example. float numbers bigger than 2^63 also needs to be printed correctly.

**Closed** 2021-01-06 09:56 UTC
